services:
  coresentinel-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coresentinel-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coresentinel-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

volumes:
  postgres_data: